"""add_last_crawled_at_to_repositories

Revision ID: 37206bd0c472
Revises: 6beac6120842
Create Date: 2025-11-03 18:24:10.605348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37206bd0c472'
down_revision: Union[str, Sequence[str], None] = '6beac6120842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_repositories_last_crawled_at'), 'repositories', ['last_crawled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_last_crawled_at'), table_name='repositories')
    op.drop_column('repositories', 'last_crawled_at')
    # ### end Alembic commands ###
