"""Initial migration: create repositories and policies tables

Revision ID: 6beac6120842
Revises: 
Create Date: 2025-11-02 07:16:22.184694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6beac6120842'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=True)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_language'), 'repositories', ['language'], unique=False)
    op.create_index(op.f('ix_repositories_stars'), 'repositories', ['stars'], unique=False)
    op.create_index(op.f('ix_repositories_updated_at'), 'repositories', ['updated_at'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), nullable=False),
    sa.Column('downvotes_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_ai_score'), 'policies', ['ai_score'], unique=False)
    op.create_index(op.f('ix_policies_created_at'), 'policies', ['created_at'], unique=False)
    op.create_index(op.f('ix_policies_filename'), 'policies', ['filename'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_repo_id'), 'policies', ['repo_id'], unique=False)
    op.create_index(op.f('ix_policies_upvotes_count'), 'policies', ['upvotes_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_upvotes_count'), table_name='policies')
    op.drop_index(op.f('ix_policies_repo_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_filename'), table_name='policies')
    op.drop_index(op.f('ix_policies_created_at'), table_name='policies')
    op.drop_index(op.f('ix_policies_ai_score'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_repositories_updated_at'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_stars'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_language'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
